/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanas_internas;

/**
 *
 * @author USUARIO
 */
public class Mis_Creaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mis_Creaciones
     */
    public Mis_Creaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(400, 150, 70, 50);

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(490, 150, 70, 50);

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(590, 150, 70, 50);

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 220, 70, 50);

        jTextField5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(490, 220, 70, 50);

        jTextField6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(590, 220, 70, 50);

        jTextField7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(400, 290, 70, 50);

        jTextField8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(490, 290, 70, 50);

        jTextField9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField9);
        jTextField9.setBounds(590, 290, 70, 50);

        jTextField10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField10);
        jTextField10.setBounds(30, 150, 70, 50);

        jTextField11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField11);
        jTextField11.setBounds(120, 150, 70, 50);

        jTextField12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField12);
        jTextField12.setBounds(220, 150, 70, 50);

        jTextField13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField13);
        jTextField13.setBounds(30, 220, 70, 50);

        jTextField14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField14);
        jTextField14.setBounds(120, 220, 70, 50);

        jTextField15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField15);
        jTextField15.setBounds(220, 220, 70, 50);

        jTextField16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField16);
        jTextField16.setBounds(30, 290, 70, 50);

        jTextField17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField17);
        jTextField17.setBounds(120, 290, 70, 50);

        jTextField18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTextField18);
        jTextField18.setBounds(220, 290, 70, 50);

        jLabel1.setText("a11");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 200, 34, 15);

        jLabel2.setText("a12");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 200, 34, 15);

        jLabel3.setText("a13");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 200, 34, 15);

        jLabel4.setText("a21");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 270, 18, 15);

        jLabel5.setText("a22");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 270, 18, 15);

        jLabel6.setText("a23");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 270, 18, 15);

        jLabel7.setText("a31");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 340, 18, 15);

        jLabel8.setText("a32");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 340, 18, 15);

        jLabel9.setText("a33");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 340, 18, 15);

        jLabel10.setText("b11");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 200, 40, 15);

        jLabel11.setText("b12");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 200, 40, 15);

        jLabel12.setText("b13");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(630, 200, 40, 15);

        jLabel13.setText("b21");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 270, 18, 15);

        jLabel14.setText("b22");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 270, 18, 15);

        jLabel15.setText("b23");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(630, 270, 18, 15);

        jLabel16.setText("b31");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(440, 340, 18, 15);

        jLabel17.setText("b32");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(530, 340, 18, 15);

        jLabel18.setText("b33");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(630, 340, 18, 15);

        jButton1.setText("SUMAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 150, 90, 25);

        jButton2.setText("RESTAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 190, 90, 25);

        jButton3.setText("Producto");
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 230, 90, 25);

        jButton4.setText("intercambia");
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 270, 90, 25);

        jButton5.setText("resetear");
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 310, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
